
#!/bin/bash
# generated by gpt
#
#
#
#Check if yay is is_installed
check_yay() {
  if ! pacman -Qs yay &> /dev/null
    echo "Yay is not installed"
  else 
    echo "yay is already installed"
  fi
}

# List of packages you want to check
packages=(
  "brightnessctl"
  "waybar"
  "hyprshot"
  "kvantum"
  "hypridle"
  "nwg-look"
  "swww"
  "wallust"
  "rofi-wayland"
  "dolphin"
  "wlogout"
  "bluez"
  "blueman"
  "pavucontrol"
  "pamixer"
  "ttf-cascadia-code-nerd"
  "otf-font-awesome"
)

# Function to check if a package is installed
is_installed() {
    pacman -Q "$1" &> /dev/null
}

# Function to install a package using pacman or yay
install_package() {
    # First try using pacman
    if ! is_installed "$1"; then
        echo "$1 is not installed. Installing..."
        # Try to install with pacman first
        sudo pacman -Sy --noconfirm --needed "$1" || \
        # If pacman fails, try yay
        yay -Sy --noconfirm --needed "$1" || \
        echo "Failed to install $1"
    else
        echo "$1 is already installed, skipping installation."
    fi
}

# Iterate over the list of packages and install if necessary
for pkg in "${packages[@]}"; do
    install_package "$pkg"
done
